version: "3.9"
services:
  chanchito-prod:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MONGO_DB_HOST=monguito-prod
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=Notes
      - MONGODB_URI=mongodb://monguito-prod:27017/Notes
      - SECRET_KEY=secreto
      - DEBUG=true
      - PORT=3000
    depends_on:
      - monguito-prod
  monguito-prod:
    image: mongo
    ports:
      - "27018:27017"
