name: Pruebas Unitarias

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    env:
        MONGO_DB_HOST: 127.0.0.1
        MONGO_DB_PORT: 27017
        MONGO_DB_NAME: Notes
        MONGODB_URI: mongodb://127.0.0.1:27017/Notes
        SECRET_KEY: secreto
        DEBUG: 'true'
        PORT: 3000
        MI_VARIABLE_SECRETA: secreto123
        
    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configuración de entorno
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalación de Dependencias
      run: npm install
      working-directory: app-notas 

    - name: Ejecución de Pruebas Unitarias
      run: |
        if npm test --forceExit; then
          echo "Las pruebas pasaron exitosamente."
        else
          echo "Las pruebas fallaron."
        fi
      working-directory: app-notas

    - name: Continuar con los siguientes pasos
      run: |
        echo "Continuando con los siguientes pasos después de las pruebas."
        # Para ver si no se queda trabado
